---

- name: Install packages
  apt:
    name: nginx-full
    state: present


- name: Template index.html
  template:
    src: templates/index.html.j2
    dest: /var/www/html/index.html

- name: Restart service to pick up config changes
  systemd:
    state: restarted
    daemon_reload: true
    name: nginx
