---

- name: Install packages
  apt:
    name: nginx-full
    state: present

- name: Remove default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Remove default site directory
  file:
    path: /var/www/html/
    state: absent

- name: Restart service to pick up config changes
  systemd:
    state: restarted
    daemon_reload: true
    name: nginx
