---
# General server tasks

- name: Update
  apt:
    update_cache: yes

- name: Upgrade
  apt:
    upgrade: safe

- name: Install base dependencies
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - gpg
      - gnupg-agent
      - software-properties-common
      - net-tools
      - patch
      - pkg-config
      - openssl
      - libssl-dev
      - cmake
      - g++
      - sudo
    state: latest

- name: Set hostname
  hostname:
    name: "{{ domain }}"

- name: Add hostname to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.1.1"
    line: "127.0.1.1 {{ mail_fqdn }} {{ domain }}"
    state: present
