---

- name: "Create group {{ ollama_xmpp_user }}"
  group:
    name: "{{ ollama_xmpp_user }}"

- name: "Create user {{ ollama_xmpp_user }}"
  user:
    name: "{{ ollama_xmpp_user }}"
    shell: "/bin/bash"
    home: "/opt/ollama-xmpp/"
    group: "{{ ollama_xmpp_user }}"

- name: Git checkout ollama python bot
  ansible.builtin.git:
    repo: 'https://github.com/gkfabs/ollama-xmpp'
    dest: /opt/ollama-xmpp
  become: yes
  become_user: "{{ ollama_xmpp_user }}"

- name: Install python requirements
  pip:
    requirements: "/opt/ollama-xmpp/requirements.txt"
    virtualenv: "/opt/ollama-xmpp/venv/"
  become: yes
  become_user: "{{ ollama_xmpp_user }}"

- name: Template /etc/systemd/system/ollama-xmpp.service
  template:
    src: templates/ollama-xmpp.service.j2
    dest: /etc/systemd/system/ollama-xmpp.service
    owner: root
    group: root
    mode: '0644'

- name: Restart service to pick up config changes
  systemd:
    state: restarted
    daemon_reload: true
    enabled: true
    name: ollama-xmpp

