---

- name: Create mail user
  user:
    name: vmail
    home: /var/vmail

- name: Create mail user sieve directory
  file:
    path: /var/vmail/sieve/global
    state: directory
    owner: vmail
    group: vmail
    mode: 0770

- name: Create mail user mailbox directory
  file:
    path: /var/vmail/mailboxes
    state: directory
    owner: vmail
    group: vmail
    mode: 0770

- name: Set mailname
  copy:
    dest: "/etc/mailname"
    content: "{{ mail_fqdn }}"

- name: Restart systemd-logind
  service:
    name: systemd-logind
    state: restarted
